In [1]:
# 导入下方会用到的所有包
import numpy as np

# Numpy基本操作之创建数组

## 1.1 使用array()函数“转换”生成数组

In [2]:
# 1.列表全是整数，木得问题
array_a1 = np.array([1,2,3,4])
array_a1

array([1, 2, 3, 4])

In [3]:
# 2.列表有一个是字符串，则全部变成字符串
array_a2 = np.array([1, '2', 3, 4])
array_a2

array(['1', '2', '3', '4'], dtype='<U11')

In [4]:
# 3.列表有一个是浮点数，则全部变成浮点数
array_a3 = np.array([1, 2.0, 3, 4])
array_a3

array([1., 2., 3., 4.])

In [5]:
# 4.列表没有数值型信息
array_a4 = np.array(['你好', '世界'])
array_a4

array(['你好', '世界'], dtype='<U2')

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

## 1.2 使用numpy.arange()生成“序列”数组

numpy.arange()的用法与Python中的range()函数用法几乎一样

In [7]:
arange_a1 = np.arange(0, 10)
arange_a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# 加入步长
arange_a2 = np.arange(0, 10, 2)
arange_a2

array([0, 2, 4, 6, 8])

## 1.3 使用np.random生成“随机”数数组

In [9]:
# 生成2行2列的随机数数组
random_a1 = np.random.random(2)
random_a1  # 返回的数组中的值均是位于[0,1)之间的小数

array([0.99670738, 0.49991555])

In [10]:
# 生成随机整数数组
random_a2 = np.random.randint(0, 10, size=(3,3)) # 指定数值范围；指定数组型号
random_a2

array([[6, 8, 9],
       [1, 0, 8],
       [1, 2, 0]])

## 1.4 使用函数生成“特殊”数组

In [11]:
# 生成“零”数组
func_a1 = np.zeros((2,3))
func_a1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 生成“一”数组
func_a2 = np.ones((3,2))
func_a2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# 生成“单位矩阵”
func_a3 = np.eye(3)
func_a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 生成指定型号的由特定数字填充的数组
func_a4 = np.full((3,2), 8)
func_a4

array([[8, 8],
       [8, 8],
       [8, 8]])