In [1]:
# 导入相关模块
import numpy as np

# 获取数组信息

## 01.获取维度信息——`.ndim`

In [2]:
a1 = np.array([1, 2, 3])
print(a1.ndim)

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2.ndim)

a3 = np.array([  # 三维数组其实就很复杂了，如果出现三维，则一般转换成一维或二维再处理！
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(a3.ndim)

1
2
3


## 02.获取形状信息——`.shape`

In [3]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


观察上述结果可知：**shape元组有几个元素，就代表有几维。**

## 03.修改形状——.`reshape`

In [4]:
a4 = a3.reshape((2, 6))
print(a4)
print(a4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [5]:
print("==============a5===============")
a5 = a3.reshape((1, 12))
print(a5)
print(a5.shape)
print(a5.ndim)

print("==============a6===============")
a6 = a3.reshape((12,))
print(a6)
print(a6.shape)
print(a6.ndim)

print("==============a7================")
a7 = a3.flatten()
print(a7)
print(a7.shape)
print(a7.ndim)

==============a5===============
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
2
==============a6===============
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
==============a7================
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


* 比较a5和a6，再次强调之前的那句话：**shape元组有几个元素，就代表有几维**。
* `flatten()`意为**扁平化**，不管你有几维，我都给你压成一维。此时也不用关心有多少个元素，简单快捷！

## 04.获取元素个数——`.size`

In [6]:
print(a1.size)
print(a2.size)
print(a3.size)

3
6
12


## 05.获取单个元素的大小——`.itemsize`

In [7]:
print("%s字节" % a1.itemsize)
print("%s字节" % a2.itemsize)
print("%s字节" % a3.itemsize)

4字节
4字节
4字节


通过size和itemsize属性便可求得一个数组所占空间的大小了（以字节为单位），只需将二者相乘便可。

# 总结
1. 数组到3维就很复杂了，不方便计算了，此时一般降维后再处理
2. 通过`ndarray.ndim`可以看到数组的维度
3. 通过`ndarray.shape`可以看到数组的形状（几行几列），**shape是一个元组，里面有几个元素，数组就是几维的**
4. 通过`ndarray.reshape()`可以修改数组的形状，条件只有一个：修改前后数组元素个数要一致，否则会报错
5. 通过`ndarray.size`可以查看数组一共有多少个元素。
6. 通过`ndarray.itemsize`可以看到数组中每个元素所占空间大小（以字节为单位）