In [1]:
# 导入相关模块
import numpy as np

# 数组的索引

## 01.花式索引

### 1.1 一维数组

In [2]:
a1 = np.arange(10)
print("原始数组：a1 = %s" % a1)
# 1.索引操作
print("【例一】索引操作：a1[4] = %s" % a1[4] )
# 2.切片操作
print("【例二】切片操作：a1[4:6] = %s" % a1[4:6])
# 3.使用步长
print("【例三】使用步长：a1[::2] = %s" % a1[::2])
# 4.使用负数来作为索引
print("【例四】负数索引：a1[-1] = %s" % a1[-1])

原始数组：a1 = [0 1 2 3 4 5 6 7 8 9]
【例一】索引操作：a1[4] = 4
【例二】切片操作：a1[4:6] = [4 5]
【例三】使用步长：a1[::2] = [0 2 4 6 8]
【例四】负数索引：a1[-1] = 9


### 1.2 多维数组

多维数组也是通过中括号来进行索引和切片。
在中括号中使用逗号进行分割，只需记住一点：**逗号前面是行，逗号后面是列**。

In [3]:
a2 = np.random.randint(0, 10, size=(4, 6))
print("原始数组：\n%s" % a2)

# 1.获取某一行
print("【例一】获取第0行：a2[0] = %s" % a2[0])

# 2.获取连续的多行
print("【例二】获取1-2行：a2[1:3] = \n%s" % a2[1:3])

# 3.获取离散的多行
print("【例三】获取第0、2、3行：a2[[0, 2, 3]]=\n%s" % a2[[0, 2, 3]])

# 4.获取某一个元素
print("【例四】获取第2行第3列元素：a2[2,3] = %s" % a2[2, 3])

# 5.获取离散的某2个元素
print("【例五】获取第1行第4列和第4行第5列这两个离散的元素：a2[[1,2],[4,5]] = %s" % a2[[1,2], [4,5]])

# 6.连续截取数组的某一部分
print("【例六】获取第1行第4列到第4行第5列之间的所有元素：a2[1:2,4:5] = \n%s" % a2[1:3, 4:6])

# 7.获取某一列
print("【例七】获取第二列：a2[:,2] = %s" % a2[:,2])

# 8.获取离散的两列
print("【例八】获取第零列和第四列：a2[:,[0,4]] = \n%s" % a2[:, [0,4]])

原始数组：
[[4 9 5 5 2 5]
 [6 3 0 8 4 8]
 [8 6 9 5 2 9]
 [2 4 0 6 6 0]]
【例一】获取第0行：a2[0] = [4 9 5 5 2 5]
【例二】获取1-2行：a2[1:3] = 
[[6 3 0 8 4 8]
 [8 6 9 5 2 9]]
【例三】获取第0、2、3行：a2[[0, 2, 3]]=
[[4 9 5 5 2 5]
 [8 6 9 5 2 9]
 [2 4 0 6 6 0]]
【例四】获取第2行第3列元素：a2[2,3] = 5
【例五】获取第1行第4列和第4行第5列这两个离散的元素：a2[[1,2],[4,5]] = [4 9]
【例六】获取第1行第4列到第4行第5列之间的所有元素：a2[1:2,4:5] = 
[[4 8]
 [2 9]]
【例七】获取第二列：a2[:,2] = [5 0 9 0]
【例八】获取第零列和第四列：a2[:,[0,4]] = 
[[4 2]
 [6 4]
 [8 2]
 [2 6]]


### 1.3 花式索引总结
* 如果数组是一维的，那其索引和切片和Python列表
* 如果是多维的，规则如下（这里以二维为例）：
    * 逗号左边是行，逗号右边是列（若只有一个值，则表示行）
    * 连续获取用切片，离散获取用中括号（比较例五和例六）

## 02.布尔索引

### 2.1 几个例子

In [4]:
# 已知有以下数组
a3 = np.arange(24).reshape((4,6))
print(a3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


**【例1】把`a3`数组中小于10的数全部取出来**

In [5]:
# 第(1)步：先做关系运算，得到布尔数组
a3 < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [6]:
# 第(2)步：再通过布尔数组进行索引
a3[a3<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**【例2】把`a3`数组中大于5且小于10的数全部取出来**

In [7]:
a3[(a3>5) & (a3<10)]  # 一步到位

array([6, 7, 8, 9])

### 2.2 布尔索引总结

* 布尔索引是通过同形状的布尔矩阵进行元素提取，为True选中，为False则不选。
* 提取条件可以有多个，此时需要逻辑运算符来连接，注意此时每个条件都要用圆括号括起来，否则会报错。

## 03.值的替换

### 3.1 花式索引替换

In [8]:
a4 = np.random.randint(0, 10, size=(3, 5))
a4

array([[8, 5, 6, 4, 2],
       [1, 1, 5, 3, 0],
       [9, 5, 8, 9, 1]])

In [9]:
# 1.替换成一个值
a4[1] = 0
a4

array([[8, 5, 6, 4, 2],
       [0, 0, 0, 0, 0],
       [9, 5, 8, 9, 1]])

In [10]:
# 2.用数组进行替换
a4[1] = np.array([1, 2, 3, 4, 5])
a4

array([[8, 5, 6, 4, 2],
       [1, 2, 3, 4, 5],
       [9, 5, 8, 9, 1]])

### 3.1 布尔索引替换

In [11]:
a4[a4<5] = 1
a4

array([[8, 5, 6, 1, 1],
       [1, 1, 1, 1, 5],
       [9, 5, 8, 9, 1]])

### 3.2 `where()`函数替换

In [12]:
pos = np.where(a4<5)
pos

(array([0, 0, 1, 1, 1, 1, 2], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [13]:
# 将a4中所有小于5的替换成0，大于等于5的替换成1
result = np.where(a4<5, 0, 1)
result

array([[1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 1, 0]])