1. 将np.arange(10)数组中的奇数全部都替换成-1。

2. 有一个4行4列的数组（比如：np.random.randint(0,10,size=(4,4))），请将其中对角线的数取出来形成一个一维数组。提示（使用np.eye）。

3. 有一个4行4列的数组，请取出其中(0,0),(1,2),(3,2)的点。

4. 有一个4行4列的数组，请取出其中2-3行（包括第3行）的所有数据。

5. 有一个8行9列的数组，请将其中1-5行（包含第5行）的第8列大于3的数全部都取出来。

In [1]:
import numpy as np

## 1.将np.arange(10)数组中的奇数全部都替换成-1。

In [2]:
a1 = np.arange(10)
a1[a1%2 != 0] = -1
a1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [3]:
a1[1::2] = -1
a1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 2.有一个4行4列的数组（比如：np.random.randint(0,10,size=(4,4))），请将其中对角线的数取出来形成一个一维数组。提示（使用np.eye）。

In [4]:
a2 = np.random.randint(0, 10, size=(4,4))
a2

array([[7, 5, 8, 0],
       [2, 4, 2, 1],
       [0, 3, 1, 7],
       [4, 5, 3, 4]])

In [5]:
eye = np.eye(4, dtype=bool)
eye


array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [6]:
a2[eye]

array([7, 4, 1, 4])

## 3.有一个4行4列的数组，请取出其中(0,0),(1,2),(3,2)的点。

In [7]:
a3 = np.random.randint(0,10, size=(4,4))
a3

array([[6, 5, 1, 9],
       [7, 3, 6, 2],
       [4, 3, 5, 7],
       [2, 0, 7, 9]])

In [8]:
a3[[0,1,3],[0,2,2]]

array([6, 6, 7])

## 4. 有一个4行4列的数组，请取出其中2-3行（包括第3行）的所有数据。

In [9]:
a4 = np.random.randint(0, 10, size=(4,4))
a4

array([[3, 3, 2, 2],
       [0, 6, 9, 1],
       [6, 9, 5, 6],
       [3, 3, 0, 6]])

In [10]:
a4[2:4]

array([[6, 9, 5, 6],
       [3, 3, 0, 6]])

## 5. 有一个8行9列的数组，请将其中1-5行（包含第5行）的第8列大于3的数全部都取出来。

In [11]:
a5 = np.random.randint(0,10, size=(8,9))
a5

array([[3, 6, 7, 4, 1, 5, 2, 5, 9],
       [9, 3, 1, 8, 5, 1, 3, 7, 2],
       [1, 0, 8, 0, 4, 4, 5, 4, 7],
       [5, 8, 9, 1, 9, 5, 1, 5, 4],
       [0, 6, 1, 8, 6, 1, 1, 7, 4],
       [1, 0, 7, 0, 6, 1, 2, 7, 2],
       [3, 3, 6, 3, 4, 3, 9, 9, 5],
       [5, 7, 9, 0, 4, 6, 7, 9, 6]])

In [12]:
data = a5[1:6,8]
data

array([2, 7, 4, 4, 2])

In [13]:
data[data>3]

array([7, 4, 4])