In [1]:
import numpy as np

## 01.数组与数的计算

In [6]:
a1 = np.random.random((3,4))
a1

array([[0.62928116, 0.37295703, 0.31856012, 0.6968846 ],
       [0.71481242, 0.64369174, 0.78137192, 0.45072004],
       [0.44628399, 0.67282452, 0.70013595, 0.84670274]])

In [10]:
a2 = a1*10
a2

array([[6.2928116 , 3.72957027, 3.18560121, 6.96884605],
       [7.14812417, 6.43691744, 7.81371918, 4.50720035],
       [4.46283993, 6.72824516, 7.00135949, 8.46702742]])

In [8]:
a3 = a2.round(2)
a3

array([[6.29, 3.73, 3.19, 6.97],
       [7.15, 6.44, 7.81, 4.51],
       [4.46, 6.73, 7.  , 8.47]])

## 02.数组与数组之间的运算

### (1)结构相同的数组之间的运算

In [11]:
a1 = np.arange(0, 24).reshape((3, 8))
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [13]:
a2 = np.random.randint(1, 10, size=(3,8))
a2

array([[6, 3, 2, 6, 2, 4, 8, 8],
       [7, 4, 4, 8, 3, 8, 8, 8],
       [9, 9, 2, 4, 9, 5, 3, 1]])

In [14]:
a1 + a2

array([[ 6,  4,  4,  9,  6,  9, 14, 15],
       [15, 13, 14, 19, 15, 21, 22, 23],
       [25, 26, 20, 23, 29, 26, 25, 24]])

In [15]:
a1 * a2

array([[  0,   3,   4,  18,   8,  20,  48,  56],
       [ 56,  36,  40,  88,  36, 104, 112, 120],
       [144, 153,  36,  76, 180, 105,  66,  23]])

### (2)与行数相同并且只有1列的数组之间的运算

In [17]:
a1 = np.random.randint(10, 20, size=(3,8))  # 3行8列
a1

array([[16, 12, 16, 15, 19, 13, 16, 10],
       [10, 11, 11, 13, 13, 17, 18, 19],
       [16, 13, 15, 17, 10, 15, 16, 15]])

In [18]:
a2 = np.random.randint(1,10,size=(3,1))  # 3行1列
a2

array([[7],
       [1],
       [3]])

In [19]:
a1 - a2

array([[ 9,  5,  9,  8, 12,  6,  9,  3],
       [ 9, 10, 10, 12, 12, 16, 17, 18],
       [13, 10, 12, 14,  7, 12, 13, 12]])

### (3)与列数相同并且只有1行的数组之间的运算

In [20]:
a1 = np.random.randint(10, 20, size=(3,8))  # 3行8列
a1

array([[14, 15, 12, 11, 10, 18, 14, 13],
       [16, 13, 17, 15, 10, 17, 18, 14],
       [19, 19, 13, 17, 12, 13, 12, 12]])

In [21]:
a2 = np.random.randint(1,10,size=(1,8)) # 1行8列
a2

array([[8, 4, 2, 4, 6, 1, 2, 5]])

In [22]:
a1 - a2

array([[ 6, 11, 10,  7,  4, 17, 12,  8],
       [ 8,  9, 15, 11,  4, 16, 16,  9],
       [11, 15, 11, 13,  6, 12, 10,  7]])

## 03.广播机制

In [24]:
a1 = np.random.randint(10, 20, size = (2,3,4))
a1

array([[[17, 18, 12, 18],
        [11, 11, 19, 16],
        [17, 15, 12, 13]],

       [[18, 14, 17, 19],
        [19, 10, 12, 17],
        [17, 16, 11, 19]]])

In [26]:
a2 = np.random.randint(1, 10, size=(3,4))
a2                     

array([[6, 6, 7, 6],
       [5, 1, 6, 6],
       [8, 7, 1, 5]])

In [27]:
a1 - a2

array([[[11, 12,  5, 12],
        [ 6, 10, 13, 10],
        [ 9,  8, 11,  8]],

       [[12,  8, 10, 13],
        [14,  9,  6, 11],
        [ 9,  9, 10, 14]]])