In [1]:
import numpy as np

In [2]:
scores = np.random.randint(0,101,size=(10,3))
scores

array([[65, 98, 67],
       [35, 85, 82],
       [50, 60, 70],
       [ 1, 24, 59],
       [69, 77, 76],
       [22,  6, 11],
       [53, 57, 35],
       [77, 14, 80],
       [10, 30, 39],
       [65, 46, 65]])

In [3]:
load_score = np.loadtxt("语数英成绩.csv",dtype=np.int, delimiter=",",skiprows=1)
load_score

array([[12,  6, 26],
       [24,  4, 38],
       [ 8, 37, 26],
       [24, 73, 39],
       [16, 99, 23],
       [38, 52, 46],
       [92,  2, 29],
       [84, 94,  9],
       [79, 83, 99],
       [39, 46, 21]])

练习.将数组a = np.random.rand(3,5)和b = np.random.rand(6,4)叠加在一起，其中a在b的上面，并且在b的第2列（下标从0开始）新增一列，用0来填充。

In [10]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
b = np.arange(100,112).reshape(3,4)
b

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [12]:
b_extend = np.hstack((b[:,0:2],np.full((3,1),0),b[:,2:]))
np.vstack((a,b_extend))

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [100, 101,   0, 102, 103],
       [104, 105,   0, 106, 107],
       [108, 109,   0, 110, 111]])