In [1]:
import numpy as np

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
a = np.random.randint(0,10,size=(5,2))
a


array([[2, 8],
       [7, 1],
       [9, 2],
       [4, 3],
       [1, 4]])

In [14]:
a[:,np.newaxis,:]

array([[[2, 8]],

       [[7, 1]],

       [[9, 2]],

       [[4, 3]],

       [[1, 4]]])

In [15]:
a[:,np.newaxis,:].shape

(5, 1, 2)