In [1]:
import numpy as np
import pandas as pd

## 01.数据对齐

### 1.1 Series

In [2]:
s1 = pd.Series(np.arange(4), index=['a', 'b','c','d'])
s1

a    0
b    1
c    2
d    3
dtype: int32

In [3]:
s2 = pd.Series(np.arange(5), index=['a', 'c','e','f','g'])
s2

a    0
c    1
e    2
f    3
g    4
dtype: int32

In [4]:
s1+s2

a    0.0
b    NaN
c    3.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

### 1.2 DataFrame

In [5]:
df1 = pd.DataFrame(np.arange(12).reshape(4,3),index=['a','b','c','d'],columns=list('ABC'))
df1

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [6]:
df2 = pd.DataFrame(np.arange(9).reshape(3,3),index=['a','d','f'],columns=list('ABD'))
df2

A  B  D
a  0  1  2
d  3  4  5
f  6  7  8

In [7]:
df1+df2

A     B   C   D
a   0.0   2.0 NaN NaN
b   NaN   NaN NaN NaN
c   NaN   NaN NaN NaN
d  12.0  14.0 NaN NaN
f   NaN   NaN NaN NaN

## 02.使用填充值的算术方法

In [8]:
s1 = pd.Series(np.arange(4), index=['a', 'b','c','d'])
s1

a    0
b    1
c    2
d    3
dtype: int32

In [9]:
s2 = pd.Series(np.arange(5), index=['a', 'c','e','f','g'])
s2

a    0
c    1
e    2
f    3
g    4
dtype: int32

In [10]:
s1+s2

a    0.0
b    NaN
c    3.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [11]:
s1.add(s2,fill_value=0)

a    0.0
b    1.0
c    3.0
d    3.0
e    2.0
f    3.0
g    4.0
dtype: float64

In [12]:
1/df1

A         B         C
a       inf  1.000000  0.500000
b  0.333333  0.250000  0.200000
c  0.166667  0.142857  0.125000
d  0.111111  0.100000  0.090909

In [13]:
df1.rdiv(1)

A         B         C
a       inf  1.000000  0.500000
b  0.333333  0.250000  0.200000
c  0.166667  0.142857  0.125000
d  0.111111  0.100000  0.090909

## 03.DataFrame和Series混合运算

In [14]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr[0]

array([0, 1, 2, 3])

In [16]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [17]:
df1

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [18]:
s1 = df1.loc['a']
s1

A    0
B    1
C    2
Name: a, dtype: int32

In [19]:
df1 - s1

A  B  C
a  0  0  0
b  3  3  3
c  6  6  6
d  9  9  9

In [20]:
s2 = df1['A']
s2

a    0
b    3
c    6
d    9
Name: A, dtype: int32

In [21]:
df1-s2

A   B   C   a   b   c   d
a NaN NaN NaN NaN NaN NaN NaN
b NaN NaN NaN NaN NaN NaN NaN
c NaN NaN NaN NaN NaN NaN NaN
d NaN NaN NaN NaN NaN NaN NaN

In [22]:
df1.sub(s2, axis='index')

A  B  C
a  0  1  2
b  0  1  2
c  0  1  2
d  0  1  2